`timescale 1ns / 1ps

// 1. Include the hash generated by your Python script
`include "stored_hash.vh"

module top #(
    parameter CLKS_PER_BIT = 2500
)(
    input  wire clk_24mhz,
    input  wire rst_pin,     // <--- Rename this to rst_pin

    input  wire uart_rx_pin,
    output wire uart_tx_pin,

    output reg  led_green,
    output reg  led_red,

    output wire       lcd_rs,
    output wire       lcd_rw,
    output wire       lcd_en,
    output wire [7:0] lcd_d
);
// --- UART Prompt Signals ---
wire [7:0] prompt_tx_data;
wire       prompt_tx_start;
wire       prompt_done;

// Instantiate the Prompt Generator
uart_prompt PROMPT_GEN (
    .clk_24mhz(clk_24mhz),
    .rst(rst),
    .tx_busy(tx_busy),
    .tx_data(prompt_tx_data),
    .tx_start(prompt_tx_start),
    .prompt_done(prompt_done)
);

// --- Echo Logic (for typed characters) ---
reg echo_start;
always @(posedge clk_24mhz) begin
    if (rst) begin
        echo_start <= 1'b0;
    end else begin
        echo_start <= 1'b0;
        // Only allow echo after the prompt finishes printing
        if (prompt_done && rx_done && !tx_busy) begin
            echo_start <= 1'b1;
        end
    end
end

// --- UART TX Signals Multiplexer ---
// If prompt is still printing, connect prompt module to UART TX.
// Once prompt is done, connect typed RX characters for echo.
wire [7:0] final_tx_data  = prompt_done ? rx_data    : prompt_tx_data;
wire       final_tx_start = prompt_done ? echo_start : prompt_tx_start;

// Connect final_tx_data and final_tx_start to your uart_tx module instance!


    // INVERT THE BUTTON HERE: 
    // If the button sends 0 when pressed, 'rst' becomes 1.
   // Change this line in top.v:
    wire rst = rst_pin; // Removed the '~' 

    // ... (The rest of your top.v code stays exactly the same!) ...
//---------------------------------------------------------
// Internal Wires connecting the modules
//---------------------------------------------------------
wire [7:0] rx_data;
wire       rx_done;
wire       parity_err;
wire       frame_err;

wire         password_ready;
wire [127:0] password;
wire [4:0]   password_length;

wire [255:0] computed_hash;
wire         hash_valid;

reg  tx_start;
wire tx_busy;
wire tx_done;

//---------------------------------------------------------
// 1. UART Receiver
//---------------------------------------------------------
uart_rx #(
    .CLKS_PER_BIT(CLKS_PER_BIT),
    .PARITY_EN(0)
) RX (
    .clk(clk_24mhz), 
    .rst(rst), 
    .rx(uart_rx_pin),
    .rx_data(rx_data), 
    .rx_done(rx_done),
    .parity_err(parity_err),
    .frame_err(frame_err)
);

//---------------------------------------------------------
// 2. UART Transmitter
//---------------------------------------------------------
uart_tx #(
    .CLKS_PER_BIT(CLKS_PER_BIT),
    .PARITY_EN(0)
) TX (
    .clk(clk_24mhz), 
    .rst(rst), 
    .tx_start(tx_start), 
    .tx_data(rx_data),
    .tx(uart_tx_pin), 
    .tx_busy(tx_busy),
    .tx_done(tx_done)
);

// Simple loopback logic: instantly transmit typed characters back to the terminal
always @(posedge clk_24mhz) begin
    if (rst)
        tx_start <= 1'b0;
    else begin
        tx_start <= 1'b0;
        if (rx_done && !tx_busy) begin
            tx_start <= 1'b1;
        end
    end
end

//---------------------------------------------------------
// 3. Password Buffer
//---------------------------------------------------------
password_buffer #(
    .MAX_LEN(16)
) BUF (
    .clk(clk_24mhz), 
    .rst(rst), 
    .rx_data(rx_data), 
    .rx_done(rx_done),
    .password_ready(password_ready), 
    .password(password), 
    .password_length(password_length)
);

//---------------------------------------------------------
// 4. SHA-256 Wrapper
//---------------------------------------------------------
sha256_wrapper SHA_WRAP (
    .clk(clk_24mhz), 
    .rst(rst),
    .password_ready(password_ready), 
    .password(password), 
    .password_length(password_length),
    .hash_out(computed_hash), 
    .hash_valid(hash_valid)
);
//---------------------------------------------------------
// 6. LCD Display Controller
//---------------------------------------------------------
wire hash_match_flag = (computed_hash == `STORED_HASH);

lcd_controller LCD_CTRL (
    .clk_24mhz(clk_24mhz),
    .rst(rst),
    .hash_valid(hash_valid),
    .hash_match(hash_match_flag), // 1 if correct, 0 if incorrect
    .lcd_rs(lcd_rs),
    .lcd_rw(lcd_rw),
    .lcd_en(lcd_en),
    .lcd_d(lcd_d)
);

//---------------------------------------------------------
// 5. The Comparator (Authentication Logic)
//---------------------------------------------------------
always @(posedge clk_24mhz) begin
    if (rst) begin
        led_green <= 0;
        led_red   <= 0;
    end else if (hash_valid) begin
        // Check if computed hash matches the macro from stored_hash.vh
        if (computed_hash == `STORED_HASH) begin
            led_green <= 1'b1; // MATCH!
            led_red   <= 1'b0;
        end else begin
            led_green <= 1'b0;
            led_red   <= 1'b1; // WRONG PASSWORD!
        end
    end
end

endmodule